[tool.ruff.lint]
extend-select = [
    "E501", # pycodestyle: line too long
    "I",    # isort
    "N",    # pep8-naming
    "D",    # pydocstyle
    "ARG",  # flake8: unused arguments
    "PD",   # pandas-vet
    "PL",   # pylint
    "UP",   # pyupgrade
]

ignore = [
    "D107", # pydocstyle: missing docstring in __init__
    "D203", # pydocstyle: 1 blank line required before class docstring
    "D213", # pydocstyle: multi-line docstring summary should start at the second line
]

[tool.ruff.lint.extend-per-file-ignores]
"tests/*.py" = [
    "D", # pydocstyle
]
